.TH "BMAApp.cpp" 3 "Pn, 25 sie 2014" "BMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BMAApp.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'BMAApp\&.h'\fP
.br
\fC#include 'BMAMain\&.h'\fP
.br
\fC#include 'wx/textfile\&.h'\fP
.br
\fC#include 'wx/file\&.h'\fP
.br
\fC#include 'wx/string\&.h'\fP
.br
\fC#include 'wx/stdpaths\&.h'\fP
.br
\fC#include 'wx/msgdlg\&.h'\fP
.br
\fC#include 'wx/wxsqlite3\&.h'\fP
.br

.SS "Funkcje"

.in +1c
.ti -1c
.RI "\fBIMPLEMENT_APP\fP (\fBBMAApp\fP)"
.br
.in -1c
.SH "Dokumentacja funkcji"
.PP 
.SS "IMPLEMENT_APP (\fBBMAApp\fP)"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla BMA\&.
