.TH "BMAApp" 3 "Pn, 25 sie 2014" "BMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BMAApp \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BMAApp\&.h>\fP
.PP
Dziedziczy wxApp\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "virtual bool \fBOnInit\fP ()"
.br
.in -1c
.SH "Dokumentacja funkcji składowych"
.PP 
.SS "bool BMAApp::OnInit ()\fC [virtual]\fP"


.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla BMA\&.
