.TH "BMAApp.h" 3 "Pn, 25 sie 2014" "BMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BMAApp.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/app\&.h>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBBMAApp\fP"
.br
.in -1c
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla BMA\&.
