.TH "BMAFrame" 3 "Pn, 25 sie 2014" "BMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BMAFrame \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BMAMain\&.h>\fP
.PP
Dziedziczy \fBGUIFrame\fP\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBRefreshList\fP (void)"
.br
.ti -1c
.RI "\fBBMAFrame\fP (wxFrame *frame)"
.br
.ti -1c
.RI "\fB~BMAFrame\fP ()"
.br
.in -1c
.SS "Metody prywatne"

.in +1c
.ti -1c
.RI "virtual void \fBOnAddItem\fP (wxRibbonButtonBarEvent &event)"
.br
.ti -1c
.RI "virtual void \fBtest\fP (wxRibbonButtonBarEvent &event)"
.br
.ti -1c
.RI "virtual void \fBOnQuit\fP (wxRibbonButtonBarEvent &event)"
.br
.ti -1c
.RI "virtual void \fBOnRefresh\fP (wxRibbonButtonBarEvent &event)"
.br
.in -1c
.SS "Dodatkowe Dziedziczone Składowe"
.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "BMAFrame::BMAFrame (wxFrame *frame)"

.SS "BMAFrame::~BMAFrame ()"

.SH "Dokumentacja funkcji składowych"
.PP 
.SS "void BMAFrame::OnAddItem (wxRibbonButtonBarEvent &event)\fC [private]\fP, \fC [virtual]\fP"

.PP
Reimplementowana z \fBGUIFrame\fP\&.
.SS "void BMAFrame::OnQuit (wxRibbonButtonBarEvent &event)\fC [private]\fP, \fC [virtual]\fP"

.PP
Reimplementowana z \fBGUIFrame\fP\&.
.SS "void BMAFrame::OnRefresh (wxRibbonButtonBarEvent &event)\fC [private]\fP, \fC [virtual]\fP"

.PP
Reimplementowana z \fBGUIFrame\fP\&.
.SS "void BMAFrame::RefreshList (void)"

.SS "void BMAFrame::test (wxRibbonButtonBarEvent &event)\fC [private]\fP, \fC [virtual]\fP"


.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla BMA\&.
