.TH "BMAMain.h" 3 "Pn, 25 sie 2014" "BMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BMAMain.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'BMAApp\&.h'\fP
.br
\fC#include 'GUIFrame\&.h'\fP
.br
\fC#include 'wx/ribbon/buttonbar\&.h'\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBBMAFrame\fP"
.br
.ti -1c
.RI "class \fBAddFrame\fP"
.br
.in -1c
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla BMA\&.
