.TH "BMAMain.cpp" 3 "Pn, 25 sie 2014" "BMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BMAMain.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'BMAMain\&.h'\fP
.br
\fC#include 'wx/msgdlg\&.h'\fP
.br
\fC#include 'sqlite\&.h'\fP
.br
\fC#include 'wx/debug\&.h'\fP
.br

.SS "Wyliczenia"

.in +1c
.ti -1c
.RI "enum \fBwxbuildinfoformat\fP { \fBshort_f\fP, \fBlong_f\fP }"
.br
.in -1c
.SS "Funkcje"

.in +1c
.ti -1c
.RI "wxString \fBwxbuildinfo\fP (\fBwxbuildinfoformat\fP format)"
.br
.in -1c
.SH "Dokumentacja typów wyliczanych"
.PP 
.SS "enum \fBwxbuildinfoformat\fP"

.PP
\fBWartości wyliczeń\fP
.in +1c
.TP
\fB\fIshort_f \fP\fP
.TP
\fB\fIlong_f \fP\fP
.SH "Dokumentacja funkcji"
.PP 
.SS "wxString wxbuildinfo (\fBwxbuildinfoformat\fPformat)"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla BMA\&.
