.TH "GUIFrame.h" 3 "Pn, 25 sie 2014" "BMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUIFrame.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/artprov\&.h>\fP
.br
\fC#include <wx/xrc/xmlres\&.h>\fP
.br
\fC#include <wx/statusbr\&.h>\fP
.br
\fC#include <wx/gdicmn\&.h>\fP
.br
\fC#include <wx/font\&.h>\fP
.br
\fC#include <wx/colour\&.h>\fP
.br
\fC#include <wx/settings\&.h>\fP
.br
\fC#include <wx/string\&.h>\fP
.br
\fC#include <wx/bitmap\&.h>\fP
.br
\fC#include <wx/image\&.h>\fP
.br
\fC#include <wx/icon\&.h>\fP
.br
\fC#include <wx/ribbon/buttonbar\&.h>\fP
.br
\fC#include <wx/ribbon/panel\&.h>\fP
.br
\fC#include <wx/ribbon/page\&.h>\fP
.br
\fC#include <wx/ribbon/control\&.h>\fP
.br
\fC#include <wx/ribbon/art\&.h>\fP
.br
\fC#include <wx/ribbon/bar\&.h>\fP
.br
\fC#include <wx/sizer\&.h>\fP
.br
\fC#include <wx/panel\&.h>\fP
.br
\fC#include <wx/dataview\&.h>\fP
.br
\fC#include <wx/textctrl\&.h>\fP
.br
\fC#include <wx/splitter\&.h>\fP
.br
\fC#include <wx/frame\&.h>\fP
.br
\fC#include <wx/stattext\&.h>\fP
.br
\fC#include <wx/slider\&.h>\fP
.br
\fC#include <wx/datectrl\&.h>\fP
.br
\fC#include <wx/dateevt\&.h>\fP
.br
\fC#include <wx/button\&.h>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBGUIFrame\fP"
.br
.RI "\fIClass \fBGUIFrame\fP\&. \fP"
.ti -1c
.RI "class \fBAddItemFrame\fP"
.br
.RI "\fIClass \fBAddItemFrame\fP\&. \fP"
.in -1c
.SS "Definicje"

.in +1c
.ti -1c
.RI "#define \fBrb_additem\fP   1000"
.br
.ti -1c
.RI "#define \fBrb_refresh\fP   1001"
.br
.ti -1c
.RI "#define \fBwww\fP   1002"
.br
.ti -1c
.RI "#define \fBrb_close\fP   1003"
.br
.in -1c
.SH "Dokumentacja definicji"
.PP 
.SS "#define rb_additem   1000"

.SS "#define rb_close   1003"

.SS "#define rb_refresh   1001"

.SS "#define www   1002"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla BMA\&.
