.TH "GUIFrame.cpp" 3 "Pn, 25 sie 2014" "BMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUIFrame.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'wx/wxprec\&.h'\fP
.br
\fC#include <wx/wx\&.h>\fP
.br
\fC#include 'GUIFrame\&.h'\fP
.br

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla BMA\&.
