.TH "sqlite.h" 3 "Pn, 25 sie 2014" "BMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'wx/wxsqlite3\&.h'\fP
.br

.SS "Funkcje"

.in +1c
.ti -1c
.RI "wxSQLite3Database * \fBinitDB\fP ()"
.br
.in -1c
.SH "Dokumentacja funkcji"
.PP 
.SS "wxSQLite3Database* initDB ()"
< Inicjalizacja bazy danych 
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla BMA\&.
