.TH "version.h" 3 "Pn, 25 sie 2014" "BMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
version.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Przestrzenie nazw"

.in +1c
.ti -1c
.RI " \fBAutoVersion\fP"
.br
.in -1c
.SS "Definicje"

.in +1c
.ti -1c
.RI "#define \fBDATE\fP   '25'"
.br
.ti -1c
.RI "#define \fBMONTH\fP   '08'"
.br
.ti -1c
.RI "#define \fBYEAR\fP   '2014'"
.br
.ti -1c
.RI "#define \fBUBUNTU_VERSION_STYLE\fP   '14\&.08'"
.br
.ti -1c
.RI "#define \fBSTATUS\fP   'Alpha'"
.br
.ti -1c
.RI "#define \fBSTATUS_SHORT\fP   'a'"
.br
.ti -1c
.RI "#define \fBMAJOR\fP   0"
.br
.ti -1c
.RI "#define \fBMINOR\fP   0"
.br
.ti -1c
.RI "#define \fBBUILD\fP   0"
.br
.ti -1c
.RI "#define \fBREVISION\fP   0"
.br
.ti -1c
.RI "#define \fBBUILDS_COUNT\fP   8"
.br
.ti -1c
.RI "#define \fBRC_FILEVERSION\fP   0,0,0,0"
.br
.ti -1c
.RI "#define \fBRC_FILEVERSION_STRING\fP   '0, 0, 0, 0\\0'"
.br
.ti -1c
.RI "#define \fBFULLVERSION_STRING\fP   '0\&.0\&.0\&.0'"
.br
.ti -1c
.RI "#define \fBBUILD_HISTORY\fP   0"
.br
.in -1c
.SH "Dokumentacja definicji"
.PP 
.SS "#define BUILD   0"

.SS "#define BUILD_HISTORY   0"

.SS "#define BUILDS_COUNT   8"

.SS "#define DATE   '25'"

.SS "#define FULLVERSION_STRING   '0\&.0\&.0\&.0'"

.SS "#define MAJOR   0"

.SS "#define MINOR   0"

.SS "#define MONTH   '08'"

.SS "#define RC_FILEVERSION   0,0,0,0"

.SS "#define RC_FILEVERSION_STRING   '0, 0, 0, 0\\0'"

.SS "#define REVISION   0"

.SS "#define STATUS   'Alpha'"

.SS "#define STATUS_SHORT   'a'"

.SS "#define UBUNTU_VERSION_STYLE   '14\&.08'"

.SS "#define YEAR   '2014'"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla BMA\&.
